# Generated by Django 3.0.6 on 2020-06-15 17:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+', max_length=128, region=None, verbose_name='Phone Number')),
                ('nationality', models.CharField(max_length=125, verbose_name='Nationality')),
                ('venture', models.CharField(choices=[('climate', 'Climate'), ('education', 'Education'), ('energy conservation', 'Energy Conservation'), ('fragility, conflict and violence', 'Fragility, Conflict and Violence'), ('poverty', 'Poverty'), ('urban development', 'Urban Development'), ('trade', 'Trade'), ('health', 'Health'), ('debt', 'Debt'), ('agriculture and food', 'Agriculture and Food'), ('governance', 'Governance'), ('water', 'Water'), ('transport', 'Transport'), ('social protection', 'Social Protection'), ('social development', 'Social Development'), ('nutrition', 'Nutrition'), ('other', 'Other')], max_length=105, verbose_name='Venture involved in')),
                ('years', models.IntegerField()),
                ('amount', models.IntegerField(verbose_name='Amount Applied for in USD')),
            ],
        ),
    ]
